#!/bin/bash

##
## Adjust this to point to the local directory where the examples are downloaded
##

export DIR=

java -cp $DIR/parametric-recursive-v3.jar:$DIR/antlr-4.4-complete.jar:$DIR/ST-4.3.jar main.Main $*
